### ISSUE TITLE
Bug - Search Function Crash

### ISSUE THREAD

**Issue by psjf** [iMinichrispy/GT-Buses#1]
App crashes when a user's search does not return any results on the building list.

Steps to reproduce:
1. Open app
2. Tap the magnifying glass
3. Enter text which does not match any building names or street addresses

<-------- Info -------->
Product: GT Buses
Version: 2.0
Build: 7022
Model: iPod touch
Model Identifier: iPod5,1
System: iPhone OS 7.0.6
Language: en_US
Location Services Enabled: 1
Location Services Status: 3
Agency: georgia-tech
Shows Arrival Time: 0
Shows Bus Identifiers: 1

**Comment by iMinichrispy** [comment]
Thanks! Fixed in a02b219
